log:
    - name: root
      level: info
      formatter: "%d%T%m%n"
      appender: 
            - type: FileLogAppender
              path: log.txt
            - type: StdoutLogAppender
    - name: system
      level: debug
      formatter: "%d%T%m%n"
      appender: 
            - type: FileLogAppender
              path: log.txt
            - type: StdoutLogAppender

system:
    port: 9900
    value: 15.1
    int_vec: 
        - 10
        - 30
    int_list: [20, 40, 50]
    int_set: [3, 4, 5]
    int_uset: [3, 4, 5]
    str_int_map: 
        k: 30
        k2: 20
        k3: 10
    str_int_umap: 
        z: 30
        z2: 20
        z3: 10
        
class: 
    person: 
        name: mystery
        age: 25
        sex: true
    map: 
        mystery1: 
            name: mystery01
            age: 25
            sex: true
        mystery2: 
            name: mystery02
            age: 26
            sex: true
    vec_map: 
        k1: 
            - name: m11
              age: 33
              sex: true
            - name: m22
              age: 44
              sex: false
        k2: 
            - name: m21
              age: 33
              sex: true
            - name: m22
              age: 44
              sex: false
